### ISSUE TITLE
Real State attributes 3.2.2 doesn't work

### ISSUE THREAD

**Issue by styly** [osclass/osclass-plugins#98] opened 2012-09-26 14:25 UTC
Real State attributes 3.2.2 by OSClass Team auto install doesn't work, 

cheers

**Comment by conejoninja** [comment] 2012-11-16 12:50
Hi styly

Could you give us some more information?

**Comment by conejoninja** [comment] 2012-11-22 11:40
Couldn't reproduce the issue.
I will close this issue until more information is provided, in that case I will open it again.

Thanks

**Closed as completed by conejoninja** 2012-11-22 11:40 UTC
Labels: realstate_attributes
