### ISSUE TITLE
more edit plugin: count bug & UI suggestion

### ISSUE THREAD

**Issue by maxxo** [osclass/osclass-plugins#83] opened 2012-06-13 11:22 UTC
When more edit plugin is enabled, a user submits an item and it is pending approval by admin before it is displayed on the site. However, even before the admin approves the item, an extra +1 count  shows for the category and location for that item. Also, if an item is edited by a user and goes back to disabled status for admin approval, the count for that item is not taken away -1 even though the item no longer appears on the front-end. Then, when the admin enables that item, an additional +1 count is given for category and location. This is very easy to duplicate and see with a test on an empty osclass site. There appear to be a number of references to this bug on the forum, for example:

http://forums.osclass.org/general-help/item-count-problem/

UI functionality suggestion for more edit plugin: Make it easier (admin > items > manage items) for the admin to view the items that have been moderated by the more edit plugin. In the manage items there is a filter (status: premium, active, enabled, spam). There is no indication to the admin for items that have been sent to moderation by the more edit plugin. If there were another status item called "moderated", it would make it very simple, quick and intuitive for the admin to see which items are awaiting approval based on the more edit plugin. As it is now, the only way to display items awaiting (more edit) moderation is for the admin to use the "enabled" status filter and search for disabled items. This might cause confusion for admins, because they will not be able to differentiate if an item has been disabled by the more edit plugin moderate feature or whether they or a user have simply disabled the item.

Please advise on the item counts bug. Thanks.

**Comment by conejoninja** [comment] 2012-11-22 09:52
I couldn't reproduce the issue, maybe this one have been already fixed. I will close this one, until more information about how to reproduce the issue is given.

Thanks

**Closed as completed by conejoninja** 2012-11-22 09:52 UTC
Labels: more_edit
