### ISSUE TITLE
Kinza QR-CODES v1.1

### ISSUE THREAD

**Issue by styly** [osclass/osclass-plugins#100] opened 2012-09-26 14:29 UTC
Hi it doesn't work that doesn't show any qr code when you add a  ads

**Comment by conejoninja** [comment] 2012-11-16 12:48
Hi styly could you give us some more information?

Otherwise I will close the issue.

**Comment by conejoninja** [comment] 2012-11-22 11:49
I couldn't reproduce the issue. It's working fine for me, did you place this code in item.php ? 

<?php show_qrcode(); ?>

**Closed as completed by conejoninja** 2012-11-22 11:49 UTC
Labels: qr_code
